"""
Planning Module
Planner chain that generates research questions and search steps
"""

import json
import re
from typing import Any, Dict, Optional, List
from rich import print as rprint

from .data_models import StageAInput
from .llm_provider import LLMProvider
from .tool_definitions import (
    PLANNING_TOOLS,
    SYSTEM_MESSAGE_PLANNER,
    build_messages_from_history
)
from .clarification import extract_first_json_block, normalize_tool_response


def planner_chain(
    llm: LLMProvider,
    research_input: StageAInput,
    conversation_history: Optional[List[Dict[str, str]]] = None,
    max_steps: int = 8
) -> Dict[str, Any]:
    """
    Generate research plan with questions and search steps
    
    Args:
        llm: LLM provider instance
        research_input: StageAInput configuration
        conversation_history: Previous conversation messages
        max_steps: Max number of search steps
    
    Returns:
        Dict with research_questions, hypotheses, steps, success_criteria
    """
    prompt = f"""Input:
- ban_chat_san_pham: {research_input.ban_chat_san_pham}
- khach_hang_muc_tieu: {research_input.khach_hang_muc_tieu}
- gia_tri_cot_loi: {research_input.gia_tri_cot_loi}
- gia_ca_chinh_sach: {research_input.gia_ca_chinh_sach}"""
    
    messages = build_messages_from_history(prompt, conversation_history, max_history=2)
    
    raw = llm.generate(
        messages=messages,
        system_message=SYSTEM_MESSAGE_PLANNER,
        tools=PLANNING_TOOLS,
        max_new_tokens=1200
    )
    rprint(f"[blue]Raw output:[/blue] {raw}")
    block = extract_first_json_block(raw)
    rprint(f"[blue]block:[/blue] {block}")
    
    # Prepare fallback steps
    fallback_steps = [
        f"Quy mo va toc do tang truong thi truong cho san pham: {research_input.ban_chat_san_pham}",
        f"Phan tich doi thu canh tranh va dinh vi cho: {research_input.ban_chat_san_pham}",
        f"Xu huong tieu dung cua khach hang: {research_input.khach_hang_muc_tieu}",
        f"Insight hanh vi mua cua: {research_input.khach_hang_muc_tieu}",
    ][:max_steps]

    if block:
        try:
            plan = json.loads(block)
            # Normalize tool calling response format
            plan = normalize_tool_response(plan)
            
            # Handle stringified JSON arrays in plan fields
            for key in ['research_questions', 'hypotheses', 'search_steps']:
                if key in plan and isinstance(plan[key], str):
                    try:
                        plan[key] = json.loads(plan[key])
                    except json.JSONDecodeError:
                        # Keep as string if can't parse
                        pass
            
            # Map search_steps to steps if needed
            if 'search_steps' in plan and 'steps' not in plan:
                plan['steps'] = plan['search_steps']
            
            plan["steps"] = plan.get("steps", [])[:max_steps]
            
            # Handle case where no steps were generated
            if not plan.get("steps") or len(plan.get("steps", [])) == 0:
                rprint("[yellow]⚠️ No search steps generated by LLM, using fallback steps[/yellow]")
                plan["steps"] = fallback_steps
            
            rprint("[green]✅ Planning completed[/green]")
            rprint(f"  Steps: {len(plan.get('steps', []))} search queries")
            return plan
        except json.JSONDecodeError:
            rprint("[red]✗ Failed to parse JSON from planner output[/red]")
            pass

    # Fallback plan
    rprint("[yellow]⚠️ Using fallback plan[/yellow]")
    
    return {
        "research_questions": ["Market research"],
        "hypotheses": ["Nguoi dung uu tien san pham an toan, minh bach thanh phan, gia hop ly"],
        "steps": fallback_steps,
        "success_criteria": ["Moi deliverable co citation URL ro rang"],
    }
