"""
Planning Module
Planner chain that generates research questions and search steps
"""

import json
import re
from typing import Any, Dict, Optional, List
from rich import print as rprint

from .data_models import StageAInput
from .llm_provider import LLMProvider
from .tool_definitions import (
    PLANNING_TOOLS,
    SYSTEM_MESSAGE_PLANNER,
    build_messages_from_history
)
from .clarification import extract_first_json_block, normalize_tool_response


def planner_chain(
    llm: LLMProvider,
    research_input: StageAInput,
    conversation_history: Optional[List[Dict[str, str]]] = None,
    max_steps: int = 8
) -> Dict[str, Any]:
    """
    Generate research plan with questions and search steps
    
    Args:
        llm: LLM provider instance
        research_input: StageAInput configuration
        conversation_history: Previous conversation messages
        max_steps: Max number of search steps
    
    Returns:
        Dict with research_questions, search_steps, and other metadata
    """
    prompt = f"""Input:
- ban_chat_san_pham: {research_input.ban_chat_san_pham}
- khach_hang_muc_tieu: {research_input.khach_hang_muc_tieu}
- gia_tri_cot_loi: {research_input.gia_tri_cot_loi}
- gia_ca_chinh_sach: {research_input.gia_ca_chinh_sach}"""
    
    messages = build_messages_from_history(prompt, conversation_history, max_history=2)
    
    raw = llm.generate(
        messages=messages,
        system_message=SYSTEM_MESSAGE_PLANNER,
        tools=PLANNING_TOOLS,
        max_new_tokens=1200
    )
    rprint(f"[blue]Raw output:[/blue] {raw}")
    block = extract_first_json_block(raw)
    rprint(f"[blue]block:[/blue] {block}")

    if block:
        try:
            plan = json.loads(block)
            # Normalize tool calling response format
            plan = normalize_tool_response(plan)
            
            # Handle stringified JSON arrays in plan fields
            for key in ['research_questions', 'search_steps']:
                if key in plan and isinstance(plan[key], str):
                    try:
                        plan[key] = json.loads(plan[key])
                    except json.JSONDecodeError:
                        # Keep as string if can't parse
                        pass
            
            # Combine research_questions and search_steps into steps
            steps = []
            if 'research_questions' in plan and plan['research_questions']:
                steps.extend(plan['research_questions'])
            if 'search_steps' in plan and plan['search_steps']:
                steps.extend(plan['search_steps'])
            
            if steps:
                plan['steps'] = steps
            elif 'steps' not in plan:
                plan['steps'] = []
            
            plan["steps"] = plan.get("steps", [])[:max_steps]
            
            # Handle case where no steps were generated
            if not plan.get("steps") or len(plan.get("steps", [])) == 0:
                rprint("[yellow]⚠️ No search steps generated by LLM, using fallback steps[/yellow]")
                plan["steps"] = generate_fallback_queries(research_input, llm, max_queries=max_steps)
                if not plan["steps"]:
                    plan["steps"] = get_generic_fallback_steps(research_input, max_steps)
            
            rprint("[green]✅ Planning completed[/green]")
            rprint(f"  Steps: {len(plan.get('steps', []))} search queries")
            return plan
        except json.JSONDecodeError:
            rprint("[red]✗ Failed to parse JSON from planner output[/red]")
            pass

    # Fallback plan when LLM main call fails
    rprint("[yellow]⚠️ LLM planning failed, generating fallback steps[/yellow]")
    fallback_steps = generate_fallback_queries(research_input, llm, max_queries=max_steps)
    
    if not fallback_steps:
        fallback_steps = get_generic_fallback_steps(research_input, max_steps)
    
    return {
        "research_questions": [f"What is the market opportunity for {research_input.ban_chat_san_pham}?"],
        "steps": fallback_steps,
        "success_criteria": ["Each finding has source URL"],
    }


def generate_fallback_queries(research_input: StageAInput, llm_provider: LLMProvider, max_queries: int = 6) -> List[str]:
    """Use LLM to generate targeted search queries from all input fields"""
    summary_prompt = f"""Based on these market research inputs, generate {max_queries} concise, specific search queries to research:
- Product/Service: {research_input.ban_chat_san_pham}
- Target Customer: {research_input.khach_hang_muc_tieu}
- Value Proposition: {research_input.gia_tri_cot_loi}
- Pricing Strategy: {research_input.gia_ca_chinh_sach}

Return ONLY the queries, one per line, no numbering or explanation."""
    
    summary_messages = [{"role": "user", "content": summary_prompt}]
    
    try:
        response = llm_provider.generate(
            messages=summary_messages,
            system_message="Bạn là chuyên gia market research. Tạo các search query ngắn gọn, cụ thể và có liên quan.",
            tools=[],
            max_new_tokens=200
        )
        # Split by lines and filter empty lines
        queries = [q.strip() for q in response.strip().split('\n') if q.strip()]
        return queries[:max_queries] if queries else []
    except Exception as e:
        rprint(f"[yellow]⚠️ Failed to generate fallback queries: {e}[/yellow]")
        return []


def get_generic_fallback_steps(research_input: StageAInput, max_steps: int = 6) -> List[str]:
    """Generic fallback steps when LLM fails completely"""
    return [
        f"Market size and trends for {research_input.ban_chat_san_pham}",
        f"Competitive analysis in {research_input.khach_hang_muc_tieu} segment",
        f"Consumer preferences and buying behavior",
        f"Pricing benchmarks and strategies",
        f"Market opportunities and gaps",
        f"Industry growth projections",
    ][:max_steps]
